import { randomUUID } from 'node:crypto'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { db } from '@ogun/db'
import { getSupportTicketEventsForPlatform, getSupportTicketForPlatform, getSupportTicketMessagesForPlatform, listActivePlatformStaffForSupport, listSupportNotificationsForPlatform } from '@ogun/db/queries'
import { ADMIN_SUPPORT_TRANSITIONS, SUPPORT_AREA_LABELS, SUPPORT_IMPACT_LABELS, SUPPORT_PRIORITY_LABELS, SUPPORT_PRIORITIES, SUPPORT_STATUS_LABELS, SUPPORT_TYPE_LABELS } from '@ogun/db/support'
import { requirePlatformPermission } from '@/lib/platform-authz'
import { roleHasPermission } from '@/lib/platform-permissions'
import { addTicketMessageAction, assignTicketAction, resolveTicketAction, retryNotificationAction, setTicketPriorityAction, transitionTicketAction } from '../actions'

export const dynamic = 'force-dynamic'

export default async function SupportDetailPage({ params, searchParams }: { params: Promise<{ ticketId: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const ctx = await requirePlatformPermission('tickets.read'); const { ticketId } = await params
  const [ticket, messages, events, notifications, allStaff, query] = await Promise.all([getSupportTicketForPlatform(db,ticketId), getSupportTicketMessagesForPlatform(db,ticketId), getSupportTicketEventsForPlatform(db,ticketId), listSupportNotificationsForPlatform(db,ticketId), listActivePlatformStaffForSupport(db), searchParams])
  if (!ticket) notFound(); const canManage = roleHasPermission(ctx.staff.role,'tickets.manage'); const staff = allStaff.filter(item => roleHasPermission(item.role,'tickets.manage')); const transitions = ADMIN_SUPPORT_TRANSITIONS[ticket.status].filter(status => status !== 'resolved')
  return <><div className="breadcrumbs"><Link href="/destek">Destek</Link> / {ticket.referenceCode}</div><div className="page-head"><div><h1>{ticket.referenceCode} · {ticket.title}</h1><p className="muted">{ticket.clinicName} · {ticket.requesterName} ({ticket.requesterEmail})</p></div><div className="header-badges"><span className="badge">{SUPPORT_STATUS_LABELS[ticket.status]}</span><span className="badge">{ticket.triagePriority ? SUPPORT_PRIORITY_LABELS[ticket.triagePriority] : 'Triage edilmedi'}</span></div></div>{query.mesaj ? <p className="notice">{query.mesaj}</p> : null}{query.hata ? <p className="error">{query.hata}</p> : null}
    <section className="card"><dl className="detail-grid"><div><dt>Tür</dt><dd>{SUPPORT_TYPE_LABELS[ticket.type]}</dd></div><div><dt>Alan</dt><dd>{SUPPORT_AREA_LABELS[ticket.area]}{ticket.otherArea ? ` · ${ticket.otherArea}` : ''}</dd></div><div><dt>Bildirilen etki</dt><dd>{SUPPORT_IMPACT_LABELS[ticket.reportedImpact]}</dd></div><div><dt>Atanan</dt><dd>{ticket.assignedName ?? 'Atanmamış'}</dd></div><div><dt>Son aktivite</dt><dd>{ticket.lastActivityAt.toLocaleString('tr-TR')}</dd></div><div><dt>Oluşturulma</dt><dd>{ticket.createdAt.toLocaleString('tr-TR')}</dd></div></dl></section>
    {canManage ? <section className="support-actions"><form action={setTicketPriorityAction} className="card compact-form"><strong>Öncelik</strong><input type="hidden" name="ticketId" value={ticket.id}/><select className="input" name="priority" defaultValue={ticket.triagePriority ?? 'P3'}>{SUPPORT_PRIORITIES.map(v => <option value={v} key={v}>{SUPPORT_PRIORITY_LABELS[v]}</option>)}</select><button className="button">Önceliği kaydet</button></form><form action={assignTicketAction} className="card compact-form"><strong>Atama</strong><input type="hidden" name="ticketId" value={ticket.id}/><select className="input" name="assignedPlatformStaffId" defaultValue={ticket.assignedPlatformStaffId ?? ''}><option value="">Atamayı kaldır</option><option value="self">Kendime ata</option>{staff.map(v => <option value={v.id} key={v.id}>{v.name} · {v.role}</option>)}</select><button className="button">Atamayı kaydet</button></form><form action={transitionTicketAction} className="card compact-form"><strong>Durum</strong><input type="hidden" name="ticketId" value={ticket.id}/><select className="input" name="status" required><option value="">Geçiş seçin</option>{transitions.map(v => <option value={v} key={v}>{SUPPORT_STATUS_LABELS[v]}</option>)}</select><button className="button" disabled={transitions.length === 0}>Durumu değiştir</button></form></section> : null}
    <section className="section"><h2>Konuşma ve iç notlar</h2><div className="support-thread">{messages.map(message => <article className={`card ${message.visibility === 'internal' ? 'internal-note' : ''}`} key={message.id}><div className="actions"><strong>{message.authorName}</strong><span className="badge">{message.visibility === 'internal' ? 'Yalnız Ogun ekibi' : 'Klinikle paylaşıldı'}</span><time className="muted">{message.createdAt.toLocaleString('tr-TR')}</time></div><p className="wrap-cell">{message.body}</p></article>)}</div></section>
    {canManage ? <><section className="support-actions section"><form action={addTicketMessageAction} className="card stack"><h2>Yanıt / iç not</h2><input type="hidden" name="ticketId" value={ticket.id}/><input type="hidden" name="clientRequestId" value={randomUUID()}/><label className="field"><span>Görünürlük</span><select className="input" name="visibility" defaultValue="public"><option value="public">Klinikle paylaş</option><option value="internal">İç not — yalnız Ogun ekibi</option></select></label><label className="field"><span>Mesaj</span><textarea className="input textarea" name="body" required minLength={2} maxLength={5000}/></label><button className="button">Mesajı ekle</button></form>{ADMIN_SUPPORT_TRANSITIONS[ticket.status].includes('resolved') ? <form action={resolveTicketAction} className="card stack"><h2>Çözüm</h2><p className="muted">Çözüm açıklaması public olarak klinikle paylaşılır ve zorunludur.</p><input type="hidden" name="ticketId" value={ticket.id}/><input type="hidden" name="clientRequestId" value={randomUUID()}/><textarea className="input textarea" name="body" required minLength={20} maxLength={5000}/><button className="button">Çözüldü olarak işaretle</button></form> : null}</section>
    <section className="section"><h2>E-posta bildirimleri</h2><div className="table-wrap"><table><thead><tr><th>Tür</th><th>Durum</th><th>Deneme</th><th>Son deneme</th><th>İşlem</th></tr></thead><tbody>{notifications.map(item => <tr key={item.id}><td>{item.type}</td><td><span className={`badge ${item.status === 'sent' ? 'success' : item.status === 'failed' ? 'failure' : ''}`}>{item.status}</span>{item.status === 'failed' && item.lastError ? <><br/><small className="muted wrap-cell">{item.lastError}</small></> : null}</td><td>{item.attemptCount}</td><td>{item.lastAttemptAt?.toLocaleString('tr-TR') ?? '—'}</td><td>{item.status === 'failed' ? <form action={retryNotificationAction}><input type="hidden" name="ticketId" value={ticket.id}/><input type="hidden" name="notificationId" value={item.id}/><button className="button">Tekrar dene</button></form> : '—'}</td></tr>)}</tbody></table></div></section></> : null}
    <details className="section"><summary>Business event history ({events.length})</summary><pre>{events.map(e => `${e.createdAt.toISOString()} · ${e.eventType} · ${e.fromStatus ?? '—'} → ${e.toStatus ?? '—'}`).join('\n')}</pre></details></>
}
