export interface OgunNutrientMapping {
  sourceCode: string
  nutrientCode: string
  sourceUnit: string
  unit: 'g' | 'mg' | 'µg' | 'kcal'
  nameTr: string
  nameEn: string
  category: 'makro' | 'vitamin' | 'mineral' | 'yağ_asidi' | 'diğer'
}

// Kaynakta porsiyon başına tam olarak bu 20 satır bulunur. Omega-3/6 toplam
// değerlerdir; ALA/linoleik asit kodlarına yanlışlıkla eşlenmez. Folik asit de
// toplam folattan ayrı tutulur.
export const ogunNutrientMap: OgunNutrientMapping[] = [
  {
    sourceCode: 'energy_kcal',
    nutrientCode: 'ENERC_KCAL',
    sourceUnit: 'kcal',
    unit: 'kcal',
    nameTr: 'Enerji',
    nameEn: 'Energy',
    category: 'makro',
  },
  {
    sourceCode: 'carbohydrate_g',
    nutrientCode: 'CHOCDF',
    sourceUnit: 'g',
    unit: 'g',
    nameTr: 'Karbonhidrat',
    nameEn: 'Carbohydrate',
    category: 'makro',
  },
  {
    sourceCode: 'protein_g',
    nutrientCode: 'PROCNT',
    sourceUnit: 'g',
    unit: 'g',
    nameTr: 'Protein',
    nameEn: 'Protein',
    category: 'makro',
  },
  {
    sourceCode: 'fat_g',
    nutrientCode: 'FAT',
    sourceUnit: 'g',
    unit: 'g',
    nameTr: 'Yağ',
    nameEn: 'Fat',
    category: 'makro',
  },
  {
    sourceCode: 'cholesterol_mg',
    nutrientCode: 'CHOLE',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Kolesterol',
    nameEn: 'Cholesterol',
    category: 'diğer',
  },
  {
    sourceCode: 'omega3_g',
    nutrientCode: 'FAN3',
    sourceUnit: 'g',
    unit: 'g',
    nameTr: 'Toplam omega-3',
    nameEn: 'Total omega-3 fatty acids',
    category: 'yağ_asidi',
  },
  {
    sourceCode: 'omega6_g',
    nutrientCode: 'FAN6',
    sourceUnit: 'g',
    unit: 'g',
    nameTr: 'Toplam omega-6',
    nameEn: 'Total omega-6 fatty acids',
    category: 'yağ_asidi',
  },
  {
    sourceCode: 'fiber_g',
    nutrientCode: 'FIBTG',
    sourceUnit: 'g',
    unit: 'g',
    nameTr: 'Lif',
    nameEn: 'Fiber',
    category: 'makro',
  },
  {
    sourceCode: 'thiamin_mg',
    nutrientCode: 'THIA',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'B1 vitamini (Tiamin)',
    nameEn: 'Thiamin',
    category: 'vitamin',
  },
  {
    sourceCode: 'riboflavin_mg',
    nutrientCode: 'RIBF',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'B2 vitamini (Riboflavin)',
    nameEn: 'Riboflavin',
    category: 'vitamin',
  },
  {
    sourceCode: 'niacin_mg',
    nutrientCode: 'NIA',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'B3 vitamini (Niasin)',
    nameEn: 'Niacin',
    category: 'vitamin',
  },
  {
    sourceCode: 'folic_acid_mcg',
    nutrientCode: 'FOLAC',
    sourceUnit: 'mcg',
    unit: 'µg',
    nameTr: 'Folik asit',
    nameEn: 'Folic acid',
    category: 'vitamin',
  },
  {
    sourceCode: 'vitamin_c_mg',
    nutrientCode: 'VITC',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'C vitamini',
    nameEn: 'Vitamin C',
    category: 'vitamin',
  },
  {
    sourceCode: 'sodium_mg',
    nutrientCode: 'NA',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Sodyum',
    nameEn: 'Sodium',
    category: 'mineral',
  },
  {
    sourceCode: 'potassium_mg',
    nutrientCode: 'K',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Potasyum',
    nameEn: 'Potassium',
    category: 'mineral',
  },
  {
    sourceCode: 'calcium_mg',
    nutrientCode: 'CA',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Kalsiyum',
    nameEn: 'Calcium',
    category: 'mineral',
  },
  {
    sourceCode: 'phosphorus_mg',
    nutrientCode: 'P',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Fosfor',
    nameEn: 'Phosphorus',
    category: 'mineral',
  },
  {
    sourceCode: 'iron_mg',
    nutrientCode: 'FE',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Demir',
    nameEn: 'Iron',
    category: 'mineral',
  },
  {
    sourceCode: 'zinc_mg',
    nutrientCode: 'ZN',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Çinko',
    nameEn: 'Zinc',
    category: 'mineral',
  },
  {
    sourceCode: 'magnesium_mg',
    nutrientCode: 'MG',
    sourceUnit: 'mg',
    unit: 'mg',
    nameTr: 'Magnezyum',
    nameEn: 'Magnesium',
    category: 'mineral',
  },
]
