import { useEffect, useMemo, useState } from 'react'
import type { DomainEntity, OgunRepositories } from '@/data/repositories'
import { FinanceScreen, type FinanceScreenData } from '@/screens/finance-screen'
import type { ExpenseFormValues, PackageFormValues } from '@/lib/validation/billing-schemas'

const text = (row: DomainEntity, key: string) => typeof row[key] === 'string' ? String(row[key]) : ''

export function LocalFinanceAdapter({ repository, month }: { repository: OgunRepositories['records']; month?: string }) {
  const [rows, setRows] = useState({ payments: [] as DomainEntity[], expenses: [] as DomainEntity[], clientPackages: [] as DomainEntity[], billingPackages: [] as DomainEntity[] })
  useEffect(() => { const load = async () => setRows({ payments: await repository.list('payments'), expenses: await repository.list('expenses'), clientPackages: await repository.list('clientPackages'), billingPackages: await repository.list('billingPackages') }); void load(); window.addEventListener('ogun-local-data-changed', load); return () => window.removeEventListener('ogun-local-data-changed', load) }, [repository])
  const now = new Date(); const [yearValue, monthValue] = (month ?? '').split('-').map(Number); const year = Number.isFinite(yearValue) && yearValue ? yearValue : now.getFullYear(); const monthIndex = Number.isFinite(monthValue) && monthValue ? monthValue - 1 : now.getMonth(); const monthKey = `${year}-${String(monthIndex + 1).padStart(2, '0')}`; const label = new Date(year, monthIndex, 1).toLocaleDateString('tr-TR', { month: 'long', year: 'numeric' })
  const data = useMemo<FinanceScreenData>(() => {
    const inMonth = (value: unknown) => { const date = new Date(String(value ?? '')); return date.getFullYear() === year && date.getMonth() === monthIndex }
    const payments = rows.payments.filter((row) => inMonth(row.paidAt)).map((row) => ({ amount: String(row.amount ?? '0'), method: String(row.method ?? 'nakit') as FinanceScreenData['payments'][number]['method'], dietitianId: text(row, 'dietitianId'), dietitianName: text(row, 'dietitianName') || 'Diyetisyen', clientPackageId: text(row, 'clientPackageId') || null }))
    return { payments, expenses: rows.expenses.filter((row) => inMonth(row.date)).map((row) => ({ id: row.id, category: text(row, 'category'), amount: String(row.amount ?? '0'), date: text(row, 'date'), description: text(row, 'description') || null })), clientPackages: rows.clientPackages.map((row) => ({ id: row.id, price: String(row.price ?? '0'), status: text(row, 'status') || 'aktif' })), clientPackagePayments: payments.map((payment) => ({ clientPackageId: payment.clientPackageId, amount: payment.amount })), billingPackages: rows.billingPackages.map((row) => ({ id: row.id, name: text(row, 'name'), sessionCount: Number(row.sessionCount ?? 0), price: String(row.price ?? '0'), validityDays: row.validityDays == null ? null : Number(row.validityDays), isActive: row.isActive !== false })) }
  }, [monthIndex, rows, year])
  async function createExpense(values: ExpenseFormValues) { try { const id = crypto.randomUUID(); await repository.upsert('expenses', { id, ...values, amount: Number(values.amount), createdAt: new Date().toISOString() }, 'expense.create'); return { success: true } } catch (reason) { return { success: false, error: String(reason) } } }
  async function createPackage(values: PackageFormValues) { try { const id = crypto.randomUUID(); await repository.upsert('billingPackages', { id, ...values, sessionCount: Number(values.sessionCount), price: Number(values.price), validityDays: values.validityDays ? Number(values.validityDays) : null, isActive: true, createdAt: new Date().toISOString() }, 'billingPackage.create'); return { success: true } } catch (reason) { return { success: false, error: String(reason) } } }
  return <FinanceScreen data={data} monthKey={monthKey} monthLabel={label} onCreateExpense={createExpense} onDeleteExpense={async (id) => { try { await repository.remove('expenses', id, 'expense.delete'); return { success: true } } catch (reason) { return { success: false, error: String(reason) } } }} onCreatePackage={createPackage} onSetPackageActive={async (id, active) => { try { const current = rows.billingPackages.find((row) => row.id === id); if (!current) throw new Error('Paket bulunamadı.'); await repository.upsert('billingPackages', { ...current, id, isActive: active }, 'billingPackage.update'); return { success: true } } catch (reason) { return { success: false, error: String(reason) } } }} />
}
