import Link from 'next/link'
import { db } from '@ogun/db'
import { listActivePlatformStaffForSupport, listSupportTicketsForPlatform, type PlatformSupportFilters } from '@ogun/db/queries'
import { SUPPORT_AREA_LABELS, SUPPORT_IMPACT_LABELS, SUPPORT_PRIORITY_LABELS, SUPPORT_PRIORITIES, SUPPORT_STATUSES, SUPPORT_STATUS_LABELS, SUPPORT_TICKET_AREAS, SUPPORT_TICKET_TYPES, SUPPORT_TYPE_LABELS } from '@ogun/db/support'
import { requirePlatformPermission } from '@/lib/platform-authz'

export const dynamic = 'force-dynamic'
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value

export default async function SupportQueuePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requirePlatformPermission('tickets.read'); const params = await searchParams
  const rawStatus = one(params.status); const rawPriority = one(params.priority); const rawType = one(params.type); const rawArea = one(params.area); const rawQueue = one(params.queue); const rawSize = Number(one(params.pageSize) ?? 25)
  const filters: PlatformSupportFilters = { search: one(params.q), status: SUPPORT_STATUSES.find((v) => v === rawStatus), priority: rawPriority === 'untriaged' ? 'untriaged' : SUPPORT_PRIORITIES.find((v) => v === rawPriority), type: SUPPORT_TICKET_TYPES.find((v) => v === rawType), area: SUPPORT_TICKET_AREAS.find((v) => v === rawArea), clinicId: one(params.clinic), assignedPlatformStaffId: one(params.assigned) || undefined, queue: rawQueue === 'all' || rawQueue === 'resolved' || rawQueue === 'untriaged' ? rawQueue : 'open', page: Number(one(params.page) ?? 1), pageSize: rawSize === 50 || rawSize === 100 ? rawSize : 25 }
  const [data, staff] = await Promise.all([listSupportTicketsForPlatform(db, filters), listActivePlatformStaffForSupport(db)])
  const href = (page: number) => { const next = new URLSearchParams(); for (const [key,value] of Object.entries(params)) if (typeof value === 'string' && key !== 'page' && value) next.set(key,value); next.set('page',String(page)); return `/destek?${next}` }
  return <><div className="page-head"><div><h1>Destek</h1><p className="muted">{data.total} destek talebi · server-side operasyon kuyruğu</p></div><div className="actions">{[['open','Açık Talepler'],['untriaged','Triage Bekleyen'],['resolved','Çözülmüş'],['all','Tümü']].map(([value,label]) => <Link className="badge" href={`/destek?queue=${value}`} key={value}>{label}</Link>)}</div></div>
    <form className="support-filter" method="get"><input type="hidden" name="queue" value={filters.queue} /><label>Arama<input className="input" name="q" defaultValue={filters.search} placeholder="Referans, başlık, klinik, kullanıcı" /></label><label>Durum<select className="input" name="status" defaultValue={filters.status ?? ''}><option value="">Tümü</option>{SUPPORT_STATUSES.map(v => <option value={v} key={v}>{SUPPORT_STATUS_LABELS[v]}</option>)}</select></label><label>Öncelik<select className="input" name="priority" defaultValue={filters.priority ?? ''}><option value="">Tümü</option><option value="untriaged">Triage edilmemiş</option>{SUPPORT_PRIORITIES.map(v => <option value={v} key={v}>{SUPPORT_PRIORITY_LABELS[v]}</option>)}</select></label><label>Tür<select className="input" name="type" defaultValue={filters.type ?? ''}><option value="">Tümü</option>{SUPPORT_TICKET_TYPES.map(v => <option value={v} key={v}>{SUPPORT_TYPE_LABELS[v]}</option>)}</select></label><label>Alan<select className="input" name="area" defaultValue={filters.area ?? ''}><option value="">Tümü</option>{SUPPORT_TICKET_AREAS.map(v => <option value={v} key={v}>{SUPPORT_AREA_LABELS[v]}</option>)}</select></label><label>Klinik ID<input className="input" name="clinic" defaultValue={filters.clinicId} /></label><label>Atanan<select className="input" name="assigned" defaultValue={filters.assignedPlatformStaffId ?? ''}><option value="">Tümü</option><option value="unassigned">Atanmamış</option>{staff.map(v => <option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Sayfa<select className="input" name="pageSize" defaultValue={data.pageSize}>{[25,50,100].map(v => <option key={v}>{v}</option>)}</select></label><button className="button">Filtrele</button></form>
    <div className="table-wrap"><table><thead><tr><th>Referans / Başlık</th><th>Klinik</th><th>Talep sahibi</th><th>Tür / Alan</th><th>Etki</th><th>Öncelik</th><th>Durum</th><th>Atanan</th><th>Son aktivite</th><th>Oluşturulma</th></tr></thead><tbody>{data.rows.length === 0 ? <tr><td colSpan={10} className="muted">Bu filtrelerle eşleşen destek talebi yok.</td></tr> : data.rows.map(ticket => <tr key={ticket.id}><td className="wrap-cell"><Link className="table-link" href={`/destek/${ticket.id}`}>{ticket.referenceCode}</Link><br />{ticket.title}</td><td>{ticket.clinicName}</td><td>{ticket.requesterName}<br /><small className="muted">{ticket.requesterEmail}</small></td><td>{SUPPORT_TYPE_LABELS[ticket.type]}<br /><small>{SUPPORT_AREA_LABELS[ticket.area]}</small></td><td>{SUPPORT_IMPACT_LABELS[ticket.reportedImpact]}</td><td>{ticket.triagePriority ? SUPPORT_PRIORITY_LABELS[ticket.triagePriority] : 'Triage edilmedi'}</td><td><span className="badge">{SUPPORT_STATUS_LABELS[ticket.status]}</span></td><td>{ticket.assignedName ?? 'Atanmamış'}</td><td>{ticket.lastActivityAt.toLocaleString('tr-TR')}</td><td>{ticket.createdAt.toLocaleDateString('tr-TR')}</td></tr>)}</tbody></table></div>
    <nav className="pagination">{data.page > 1 ? <Link href={href(data.page - 1)}>Önceki</Link> : null}<span>{data.page} / {Math.max(1,Math.ceil(data.total/data.pageSize))}</span>{data.page * data.pageSize < data.total ? <Link href={href(data.page + 1)}>Sonraki</Link> : null}</nav></>
}
